In [27]:
import pandas as pd
import numpy as np

In [28]:
pd.__version__

'1.4.2'

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-17 07:03:27--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  --.-KB/s    in 0.04s   

2023-09-17 07:03:27 (30.3 MB/s) - ‘housing.csv’ saved [1423529/1423529]



In [4]:
df = pd.read_csv('housing.csv')

In [5]:
len(df.columns)

10

In [31]:
len(df[df.total_rooms.isnull()]),len(df[df.total_bedrooms.isnull()])

(0, 207)

In [32]:
df.ocean_proximity.unique(),len(df.ocean_proximity.unique())

(array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
       dtype=object),
 5)

In [33]:
df[df.ocean_proximity=="NEAR BAY"].median_house_value.mean()

259212.31179039303

In [34]:
df.total_bedrooms.mean()

537.8705525375618

In [36]:
df.fillna(537.871).total_bedrooms.mean()

537.8705570251923

In [41]:
X=df[df.ocean_proximity=="ISLAND"][['housing_median_age', 'total_rooms', 'total_bedrooms']].to_numpy()

In [42]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [52]:
XTX = X.T @ X

In [53]:
np.linalg.inv(XTX)

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [55]:
y = [950, 1300, 800, 1000, 1300]

In [66]:
w=(np.linalg.inv(XTX) @ X.T).dot(y)

In [67]:
w

array([23.12330961, -1.48124183,  5.69922946])